name: Code Owner Approval

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Require Code Owner Approval
        uses: actions/require-code-owner-approval@v1
        with:
          branches: main