name: assign-label

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened

jobs:
  assign-label:
    uses: kubra-hq/change-approval-wf/.github/workflows/assign-label.yml@main
    with:
      config-path: ".github/config/auto-label-pulls.json"
    secrets:
      token: ${{ secrets.GHACTION_TOKEN }}
