name: Assign label

# On a Pull request open event, this GitHub action will be triggered.
on:
  workflow_call:
    inputs:
      config-path:      # The variable contains the configuration path for the critical branch list "/config/auto-label-pulls.json"
        required: true
        type: string
    secrets:
      token:            # The variable contains the GitHub token to perform actions
        required: true
      

jobs:
  assign-label:

    # The steps below will only be executed if the target branch is 'main' OR 'master' to denote a Production update.
    if: ${{ (github.event.pull_request.base.ref == 'main') || (github.event.pull_request.base.ref == 'master') || (github.event.pull_request.base.ref == 'main/prod-cde') }}
    runs-on: ubuntu-latest
    steps:
      - name: Assign labels
        uses: kubra-hq/change-approval-wf@marketplace-script
        
        # Copied marketplace workflow in same repository with branch name "marketplace-script"
        with:
          token: ${{ secrets.token }}
          config-path: ${{ inputs.config-path }}