name: Pull Request Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Risk Level
        run: |
          if [ -z "${RISK_LEVEL}" ]; then
            echo "Error: Risk Level is not set"
            exit 1
          fi
      - name: Check Impact
        run: |
          if [ -z "${IMPACT}" ]; then
            echo "Error: Impact is not set"
            exit 1
          fi
      - name: Check Checkboxes
        run: |
          if [ -z "${CHECKBOXES}" ]; then
            echo "Error: Not all checkboxes are selected"
            exit 1
          fi
          checkboxes=("You have verified that this pull request fulfills the story's scope/description."
            "You have verified that this pull request fulfills all story acceptance criteria."
            "You have created any necessary Integration Tests that verify the code being changed appropriately."
            "There is sufficient documentation of this change to satisfy the Product Manager of this service."
            "Authorized personnel have reviewed this code and approved it."
            "This change is ready for Demo to the product manager & rest of the team.")
          for checkbox in "${checkboxes[@]}"; do
            if [ -z "${checkbox}" ]; then
              echo "Error: Checkbox '${checkbox}' is not selected"
              exit 1
            fi
          done

      - name: Success
        run: |
          echo "Pull Request is valid. Ready to merge!"
