name: Enforce Pull Request Checks

on:
  pull_request:

jobs:
  enforce_checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check Risk Level
        uses: gr2m/issue-triage@v4
        with:
          labels: risk

      - name: Check Impact
        uses: gr2m/issue-triage@v4
        with:
          labels: impact

      - name: Check Merge Checklist
        uses: juliangruber/goreview-labels@v2
        with:
          required-labels: "verified"
          label: "verified"
          context: "(For Pull Request creator only!) Please check these once you have verified each of them. When done, you'll be able to merge."

      - name: Fail workflow if checks are not met
        uses: actions/github-script@v6
        with:
          script: |
            github.actions.getIssue({ issue_number: context.issue.number })
              .then(issue => {
                const riskLabels = issue.labels.filter(label => label.name.toLowerCase() === 'risk');
                const impactLabels = issue.labels.filter(label => label.name.toLowerCase() === 'impact');
                const verifiedLabels = issue.labels.filter(label => label.name === 'verified');

                if (riskLabels.length === 0 || impactLabels.length === 0 || verifiedLabels.length !== 6) {
                  throw new Error('Pull request does not meet all requirements. Please fill out Risk Level, Impact, and verify all checkboxes.');
                }
              });
