name: Pull Request Checks

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-pr-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Risk Level
        uses: actions/github-script@v6
        with:
          script: |
            const templateFile = '.github/pull_request_template.md';
            const templateContent = core.getInput('template_content', { required: true });
            const riskLevelRegex = /\[x\]\sLow|\[x\]\sModerate|\[x\]\sHigh/;

            if (!riskLevelRegex.test(templateContent)) {
              core.setFailed('Risk Level must be selected.');
            }

      - name: Check Impact
        uses: actions/github-script@v6
        with:
          script: |
            const templateFile = '.github/pull_request_template.md';
            const templateContent = core.getInput('template_content', { required: true });
            const impactRegex = /\[x\]\sLow|\[x\]\sModerate|\[x\]\sHigh/;

            if (!impactRegex.test(templateContent)) {
              core.setFailed('Impact must be selected.');
            }

      - name: Check PR Creator Checkboxes
        uses: actions/github-script@v6
        with:
          script: |
            const templateFile = '.github/pull_request_template.md';
            const templateContent = core.getInput('template_content', { required: true });
            const checkboxesRegex = /\[x\]\sYou have verified that this pull request fulfills the story's scope\/description./g;
            const matches = templateContent.match(checkboxesRegex);

            if (!matches || matches.length !== 6) {
              core.setFailed('All checkboxes must be selected.');
            }

      - name: Fail workflow if checks not met
        uses: actions/github-script@v6
        if: github.event.action != 'closed'
        with:
          script: core.setFailed('Risk Level, Impact, and all checkboxes must be filled!')
