name: Check PR Template

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check-template:
    runs-on: ubuntu-latest
    steps:
    - name: Get PR content
      id: get_pr
      uses: actions/github-script@v6
      with:
        script: |
          const { data: pullRequest } = await github.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
          });
          return pullRequest.body;

    - name: Validate PR template
      id: validate_template
      run: |
        PR_BODY="${{ steps.get_pr.outputs.result }}"
        
        RISK_LEVEL=false
        IMPACT=false
        CHECKBOXES=false

        if [[ "$PR_BODY" =~ "- $$x$$ Low" || "$PR_BODY" =~ "- $$x$$ Moderate" || "$PR_BODY" =~ "- $$x$$ High" ]]; then
          RISK_LEVEL=true
        fi

        if [[ "$PR_BODY" =~ "- $$x$$ Low" || "$PR_BODY" =~ "- $$x$$ Moderate" || "$PR_BODY" =~ "- $$x$$ High" ]]; then
          IMPACT=true
        fi

        if [[ "$PR_BODY" =~ "- $$x$$ You have verified that this pull request fulfills the story's scope/description." && \
              "$PR_BODY" =~ "- $$x$$ You have verified that this pull request fulfills all story acceptance criteria." && \
              "$PR_BODY" =~ "- $$x$$ You have created any necessary Integration Tests that verify the code being changed appropriately." && \
              "$PR_BODY" =~ "- $$x$$ There is sufficient documentation of this change to satisfy the Product Manager of this service." && \
              "$PR_BODY" =~ "- $$x$$ Authorized personnel have reviewed this code and approved it." && \
              "$PR_BODY" =~ "- $$x$$ This change is ready for Demo to the product manager & rest of the team." ]]; then
          CHECKBOXES=true
        fi

        if [[ "$RISK_LEVEL" == true && "$IMPACT" == true && "$CHECKBOXES" == true ]]; then
          exit 0
        else
          exit 1
        fi
