name: PR Checks

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-pr-template:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check Risk Level
        uses: gr2m/github-action-markdown-checkbox@v2
        with:
          file: pull_request_template.md
          pattern: 'Risk Level'
          failure-message: 'Please select a Risk Level'

      - name: Check Impact
        uses: gr2m/github-action-markdown-checkbox@v2
        with:
          file: pull_request_template.md
          pattern: 'Impact'
          failure-message: 'Please select an Impact'

      - name: Check PR Creator Checkboxes
        uses: gr2m/github-action-markdown-checkbox@v2
        with:
          file: pull_request_template.md
          pattern: '\[ \] You have verified'
          checkboxes: 6
          failure-message: 'Please check all 6 checkboxes under "For Pull Request creator only!"'

      - name: Fail workflow if any check failed
        uses: actions/github-script@v6
        with:
          github-script: |
            if (github.event.issue.pull_requests && github.event.issue.pull_requests[0].merged === false) {
              core.setFailed('Pull Request cannot be merged due to missing information in pull_request_template.md')
            }
