name: PR Checklist Verification

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check_pr_template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify PR Checklist
        id: verify
        run: |
          TEMPLATE_FILE=".github/pull_request_template.md"
          CONTENT=$(cat "$TEMPLATE_FILE")

          REQUIRED_CHECKBOXES=(
            "- You have verified that this pull request fulfills the story's scope/description."
            "- You have verified that this pull request fulfills all story acceptance criteria."
            "- You have created any necessary Integration Tests that verify the code being changed appropriately."
            "- There is sufficient documentation of this change to satisfy the Product Manager of this service."
            "- Authorized personnel have reviewed this code and approved it."
            "- This change is ready for Demo to the product manager & rest of the team."
          )

          for CHECKBOX in "${REQUIRED_CHECKBOXES[@]}"; do
            if ! grep -qF "$CHECKBOX" "$TEMPLATE_FILE"; then
              echo "Error: Checklist item not found - $CHECKBOX"
              exit 1
            fi
          done
          
          echo "All required checklist items found."

      - name: Check Risk Level
        id: check_risk
        run: |
          RISK_LEVEL=$(grep -E "Low|Moderate|High" .github/pull_request_template.md | grep -o "Low\|Moderate\|High" || true)

          if [ -z "$RISK_LEVEL" ]; then
            echo "Error: No Risk Level option checked."
            exit 1
          else
            echo "Risk Level checked: $RISK_LEVEL"
          fi

      - name: Check Impact
        id: check_impact
        run: |
          IMPACT=$(grep -E "Low|Moderate|High" .github/pull_request_template.md | grep -o "Low\|Moderate\|High" || true)

          if [ -z "$IMPACT" ]; then
            echo "Error: No Impact option checked."
            exit 1
          else
            echo "Impact checked: $IMPACT"
          fi

      - name: Success
        if: always()
        run: echo "Pull Request meets all requirements, ready to merge."
