name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check_pr_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check PR template
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          # Check Risk Level
          if ! echo "$PR_BODY" | grep -q "\- \[x\] Low" && ! echo "$PR_BODY" | grep -q "\- \[x\] Moderate" && ! echo "$PR_BODY" | grep -q "\- \[x\] High"; then
            echo "Error: Risk Level not selected"
            exit 1
          fi
          
          # Check Impact
          if ! echo "$PR_BODY" | grep -q "\- \[x\] Low" && ! echo "$PR_BODY" | grep -q "\- \[x\] Moderate" && ! echo "$PR_BODY" | grep -q "\- \[x\] High"; then
            echo "Error: Impact not selected"
            exit 1
          fi
          
          # Check all 6 checkboxes
          REQUIRED_CHECKS=6
          CHECKED_COUNT=$(echo "$PR_BODY" | grep -c "\- \[x\] You have")
          if [ $CHECKED_COUNT -ne $REQUIRED_CHECKS ]; then
            echo "Error: Not all required checkboxes are checked. Found $CHECKED_COUNT out of $REQUIRED_CHECKS."
            exit 1
          fi
          
          echo "All checks passed"

      - name: Block PR
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              body: 'Please ensure all required fields are filled and checkboxes are checked before merging.',
              event: 'REQUEST_CHANGES'
            })
