name: Verify PR Checklist

on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Verify PR Checklist
        id: verify
        run: |
          TEMPLATE_FILE=".github/pull_request_template.md"
          CONTENT=$(cat "$TEMPLATE_FILE")

          REQUIRED_CHECKBOXES=(
            "- \[x] You have verified that this pull request fulfills the story's scope/description."
            "- \[x] You have verified that this pull request fulfills all story acceptance criteria."
            "- \[x] You have created any necessary Integration Tests that verify the code being changed appropriately."
            "- \[x] There is sufficient documentation of this change to satisfy the Product Manager of this service."
            "- \[x] Authorized personnel have reviewed this code and approved it."
            "- \[x] This change is ready for Demo to the product manager & rest of the team."
          )

          for CHECKBOX in "${REQUIRED_CHECKBOXES[@]}"; do
            if ! grep -q "$CHECKBOX" "$CONTENT"; then
              echo "Error: Checklist item not selected - $CHECKBOX"
              exit 1
            fi
          done

          echo "All required checklist items selected."
