name: Require Successful Terraform Plan for Merge

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 'latest'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: terraform-plan
        run: |
          terraform plan -no-color > plan_output.txt
        continue-on-error: true

      - name: Check Terraform Plan Output
        id: check-output
        run: |
          if grep -q 'No changes' plan_output.txt; then
            echo "No changes detected"
            echo "::set-output name=status::success"
          else
            echo "Changes detected"
            echo "::set-output name=status::failure"
          fi

      - name: Report Terraform Plan Status
        uses: actions/github-script@v6
        if: ${{ steps.check-output.outputs.status == 'failure' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.pulls.createReview({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              pull_number: github.context.issue.number,
              event: 'REQUEST_CHANGES',
              body: 'Terraform plan has changes. Please fix before merging.'
            });

      - name: Approve PR if No Changes
        if: ${{ steps.check-output.outputs.status == 'success' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.pulls.createReview({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              pull_number: github.context.issue.number,
              event: 'APPROVE',
              body: 'Terraform plan has no changes. Ready for merging.'
            });
