name: Terraform Plan and Merge

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-plan-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Run Terraform Plan
        run: terraform plan -no-color

      - name: Merge PR if Terraform Plan succeeds
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: merge
          client-payload: '{"ref":"main","sha":"${{ github.sha }}","merge_method":"rebase"}'