name: Restricted Approval

on:
  pull_request:
    branches:
      - main # or your default branch

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Validate code
        run: echo "Add your validation steps here"

  restricted_approval:
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Check approval
        id: check-approval
        uses: actions/github-script@v4
        with:
          script: |
            const { GITHUB_TOKEN } = process.env;
            const octokit = github.getOctokit(GITHUB_TOKEN);

            const response = await octokit.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const approvers = response.data.filter(review => review.state === "APPROVED");
            const approvedBySpecificUser = approvers.some(review => review.user.email === "abc@gmail.com");

            if (!approvedBySpecificUser) {
              core.setFailed("The pull request must be approved by abc@gmail.com before merging.");
            }

      - name: Prevent merge without specific user's approval
        if: failure()
        run: exit 1
