name: Terraform Cloud Plan

on:
  push:
    branches:
      - main

jobs:
  terraform-cloud-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Terraform Cloud
        uses: appleboy/terraform-cloud-login-action@v1
        with:
          token: ${{ secrets.TERRAFORM_TOKEN }}
          organization: your-org-name
          workspace: your-workspace-name

      - name: Run Terraform Cloud Plan
        run: |
          terraform login ${{ secrets.TERRAFORM_TOKEN }}
          terraform plan -input=false
