name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
  verify:
    needs: [build,]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check all statuses
        run: |
          gh run list --json status,conclusion,name | jq -r '.[] | select(.conclusion != "success") | .name' | tee /dev/stderr | ifne exit 1

      - name: All checks passed
        run: echo "All checks passed. Proceed with merge."
