name: Terraform Plan Check

on:
  pull_request:
    branches:
      - main      # This will trigger the workflow for PRs targeting the 'main' branch
    paths:
      - '**/*.tf'  # Trigger this action only if Terraform files change
    types:
      - opened
      - synchronize
      - reopened

jobs:
  terraform:
    name: Run Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5  # Specify your Terraform version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan > terraform.plan

      - name: Upload Terraform Plan Output
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: terraform.plan

      - name: Check for Plan Success
        run: |
          if grep -q "No changes." terraform.plan; then
            echo "Terraform plan successful."
          else
            echo "Terraform plan failed."
            exit 1
          fi
