name: Prevent Direct Pushes to Main

on: 
  push:
    branches:
      - main

jobs:
  prevent_push:
    runs-on: ubuntu-latest
    steps:
    - name: Fail if this is a push to the main branch
      run: |
        echo "Direct pushes to the main branch are not allowed."
        exit 1
