name: Terraform Cloud Plan

on:
  push:
    branches:
      - main

jobs:
  terraform-cloud-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Terraform Cloud
        uses: hashicorp/setup-terraform@v2
        with:
          cloud_token: ${{ secrets.TERRAFORM_TOKEN }}
          cloud_hostname: app.terraform.io

      - name: Run Terraform Cloud Plan
        run: |
          terraform plan -input=false
