name: Terraform Code Review

on:
  pull_request:
    branches:
      - main # or your default branch

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0 # Adjust the version as needed

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Run terraform fmt
        run: terraform fmt -check

  mandatory_approval:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Enforce code review
        uses: actions/github-script@v4
        with:
          script: |
            const { GITHUB_TOKEN } = process.env;
            const octokit = github.getOctokit(GITHUB_TOKEN);

            const response = await octokit.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const approvals = response.data.filter(review => review.state === "APPROVED");

            if (approvals.length === 0) {
              core.setFailed("No approval found for this pull request");
            }

      - name: Prevent merge without approval
        if: failure()
        run: exit 1