name: Terraform Plan and Merge

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-plan-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 'latest'

      - name: Authenticate with Terraform Cloud
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_TOKEN }}
        run: echo "Terraform Cloud token is set."

      - name: Terraform Init
        run: terraform init

      - name: Run Terraform Plan
        id: terraform-plan
        run: terraform plan -no-color

      - name: Merge PR if Terraform Plan succeeds
        if: success()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pull_number = github.context.issue.number;
            await github.pulls.merge({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              pull_number: pull_number,
              merge_method: 'rebase'
            });
