name: Check Status Checks

on:
  pull_request:
    branches:
      - main

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check status checks
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          script: |
            const { data: checkRuns } = await github.rest.checks.listForRef({
              owner: github.context.repo.owner.login,
              repo: github.context.repo.name,
              ref: github.context.sha
            });

            const allChecksPassed = checkRuns.check_runs.every(check => check.conclusion === 'success');

            if (allChecksPassed) {
              console.log('All status checks have passed!');
            } else {
              console.log('Not all status checks have passed.');
              core.setFailed('Not all status checks have passed.');
            }