name: Require Passing Checks for Merge

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run checks
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Require passing checks
        if: github.event.pull_request.state == 'opened' && github.event.action == 'review_requested'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const checks = await github.checks.listForRef({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              ref: github.context.pullRequest.head.sha
            });

            const failingChecks = checks.data.check_runs.filter(check => check.status === 'completed' && check.conclusion !== 'success');

            if (failingChecks.length > 0) {
              github.issues.createComment({
                owner: github.context.repo.owner,
                repo: github.context.repo.repo,
                issue_number: github.context.pullRequest.number,
                body: 'Cannot merge until all checks pass'
              });

              github.pulls.update({
                owner: github.context.repo.owner,
                repo: github.context.repo.repo,
                pull_number: github.context.pullRequest.number,
                state: 'blocked'
              });
            } else {
              github.pulls.update({
                owner: github.context.repo.owner,
                repo: github.context.repo.repo,
                pull_number: github.context.pullRequest.number,
                state: 'unblocked'
              });
            }